@startuml
title Reset Password Process

skinparam ParticipantBackgroundColor #EEEEEE
skinparam ParticipantBorderColor #333333
skinparam sequenceAltBackgroundColor #FFFFFF

actor User #lightblue
participant "User Service" as UserService  #FFA500
participant "Verification Service" as VerificationService  #DDA0DD
participant "Cache Service" as CacheService  #FF6347
participant "Notification Service" as NotificationService  #DDA0DD

User -> UserService: Enter Email
activate User #lightblue
activate UserService #FFA500

UserService -> UserService: Check if User Exist
par verification 
  UserService -> VerificationService: Send email and user id
  activate VerificationService #DDA0DD
  
  VerificationService -> CacheService: Get the token cached
  activate CacheService #FF6347
  CacheService --> VerificationService: "Get the cached email"
  
  alt cache exist 
    activate NotificationService #DDA0DD
    alt cooldown passed 
      alt retries < 5 
        VerificationService -> CacheService: "Set retry+1, new Code/token"
        VerificationService --> UserService: Send token
        alt Exist 
          UserService -> NotificationService: Send verification email
        end
        UserService --> User: successful
      else retries >=5 
        VerificationService -> CacheService: "Set 1-hour cooldown"
        VerificationService --> UserService: Send token
        alt Exist 
          UserService -> NotificationService: Send verification email
        end
        UserService --> User: successful
      end
    else cooldown exist 
      VerificationService --> User: Error with remaining time
    end
  else cache not exist 
    VerificationService -> CacheService: Save email, code, token
    VerificationService --> UserService: Send Code
    alt Exist 
      UserService -> NotificationService: Send verification email
    end
    deactivate NotificationService
    UserService --> User: successful
  end
  deactivate CacheService
  deactivate VerificationService

deactivate UserService
deactivate User

' Get token from code process
User -> UserService: Send Code, Email
activate User #lightblue
activate UserService #FFA500

VerificationService -> CacheService: Check cache
activate CacheService #FF6347
CacheService --> VerificationService: Get cache
alt Code valid 
  VerificationService --> User: Send Token
else invalid 
  VerificationService --> User: Verification error
end
deactivate CacheService
deactivate UserService
deactivate User

' Change Password process
User -> UserService: Send Token, Email, Password
activate User #lightblue
activate UserService #FFA500

VerificationService -> CacheService: Check cache
activate CacheService #FF6347
CacheService --> VerificationService: Get cache
alt Token valid
  VerificationService -> CacheService: Delete data
  VerificationService --> UserService: Send User Id
  UserService -> UserService: Hash and update password
  UserService --> User: Password updated
else invalid
  VerificationService --> User: Verification error
end
deactivate CacheService
deactivate UserService
deactivate User
@enduml